<%
	Dim strConnectionString
	
	strConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0; Data Source=C:\Users\Arjan\Documents\GitHub\ttkaart-v1\data\rankings.mdb"
	
	
	Dim arrCrawlerUserAgents
	
	arrCrawlerUserAgents = Array("008 0.83","008/0.83","ABACHOBOT","ACCOONA-AI-AGENT","ADDSUGARSPIDERBOT", _
							"ANYAPEXBOT","ARACHMO","B-L-I-T-Z-B-O-T","BAIDUSPIDER","BECOMEBOT", _
							"BESLISTBOT","BILLYBOBBOT","BIMBOT","BINGBOT","BLITZBOT","BOITHO.COM-DC", _
							"BOITHO.COM-ROBOT","BTBOT","CATCHBOT","CERBERIAN DRTRS","CHARLOTTE", _
							"CONVERACRAWLER","COSMOS","COVARIO","DATAPARKSEARCH","DIAMONDBOT","DISCOBOT", _
							"DOTBOT","EMERALDSHIELD.COM WEBBOT","ENVOLK[ITS]SPIDER","ESPERANZABOT", _
							"EXABOT","FAST ENTERPRISE CRAWLER","FAST-WEBCRAWLER","FDSE ROBOT", _
							"FINDLINKS","FURLBOT/FURL SEARCH","FYBERSPIDER","G2CRAWLER","GAISBOT", _
							"GALAXYBOT","GENIEBOT","GIGABOT","GIRAFABOT","GOOGLEBOT","GURIJIBOT", _
							"HAPPYFUNBOT","HL_FTIEN_SPIDER","HOLMES","HTDIG","IASKSPIDER","IA_ARCHIVER", _
							"ICCRAWLER","ICHIRO","IGDESPYDER","IRLBOT","ISSUECRAWLER","JAXIFIEDBOT", _
							"JXYOBOT","KOEPABOT","L.WEBIS","LAPOZZBOT","LARBIN","LDSPIDER","LEXXEBOT", _
							"LINGUEE BOT","LINKWALKER","LMSPIDER","LWP-TRIVIAL","MABONTLAND", _
							"MAGPIE-CRAWLER","MEDIAPARTNERS-GOOGLE","MJ12BOT","MNOGOSEARCH", _
							"MOGIMOGI","MOJEEKBOT","MOREOVERBOT","MORNING PAPER","MSNBOT","MSRBOT", _
							"MVACLIENT","MXBOT","NETRESEARCHSERVER","NETSEER CRAWLER","NEWSGATOR", _
							"NG-SEARCH","NICEBOT","NOXTRUMBOT","NUSEARCH SPIDER","NUTCHCVS","NYMESIS", _
							"OBOT","OEGP","OMGILIBOT","OMNIEXPLORER_BOT","OOZBOT","ORBITER", _
							"PAGEBITSHYPERBOT","PEEW","POLYBOT","POMPOS","POSTPOST","PSBOT","PYCURL","QSEERO", _
							"RADIAN6_DEFAULT","RAMPYBOT","RUFUSBOT","SANDCRAWLER","SBIDER","SCOURJET", _
							"SCRUBBY","SEARCHSIGHT","SEEKBOT","SEMANTICDISCOVERY","SENSIS WEB CRAWLER", _
							"SEOCHAT","SEZNAMBOT","SHIM-CRAWLER","SHOPWIKI","SHOULA","SILK","SITEBOT","SNAPPY", _
							"SOGOU SPIDER","SOSOSPIDER","SPEEDY SPIDER","SQWORM","STACKRAMBLER","SUGGYBOT", _
							"SURVEYBOT","SYNOOBOT","ASKJEEVES/TEOMA","TERRAWIZBOT","THESUBOT", _
							"THUMBNAIL.CZ ROBOT","TINEYE","TRUWOGPS","TURNITINBOT","TWEETEDTIMES BOT", _
							"TWENGABOT","UPDATED","URLFILEBOT","VAGABONDO","VOILABOT","VORTEX","VOYAGER", _
							"VYU2","WEBCOLLAGE","WEBSQUASH","WF84","WOFINDEICH ROBOT","WOMIPEFACTORY", _
							"XALDON_WEBSPIDER","YACYBOT","SLURP","YAHOOSEEKER","YANDEXBOX","YASAKLIBOT", _
							"YETI","YODAOBOT","YOOGLIFETCHAGENT","YOUDAOBOT","ZAO","ZEALBOT","ZSPIDER", _
							"ZYBORG")
%>